name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: entepotenz/keep-github-actions-alive-min-dependencies@v1
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
